# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-LiveDepartureBoards
version:      0.03
version_from: lib/WWW/LiveDepartureBoards.pm
installdirs:  site
requires:
    DateTime:                      0
    LWP:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
